### ISSUE TITLE
Putty doesn't start

### ISSUE THREAD

**Issue by arozehnal** [dsone/remote-ssh#8]
I have installed Putty in d:\U\SSH\Putty_0.67. 

My PATH:
Path=d:\U\SSH\Putty_0.67;C:\Program Files\IBM Informix Client-SDK\bin;C:\Program Files\IBM Informix Software Bundle\bin;D:\Devel\STAF\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\U\Xshell 6\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\U\TortoiseSVN\bin;D:\Devel\perl\Dwimperl\perl\bin;D:\Devel\perl\Dwimperl\perl\site\bin;D:\Devel\perl\Dwimperl\c\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;D:\U\Git\cmd;D:\U\TortoiseGit\bin;D:\Kancl\Pandoc\;D:\Devel\Python\Python37-32\Scripts\;D:\Devel\Python\Python37-32\;C:\Users\RO\scoop\shims;C:\Users\RO\AppData\Local\Microsoft\WindowsApps;C:\Users\RO\AppData\Local\Microsoft\WindowsApps;C:\Users\RO\AppData\Local\atom\bin

OS: Win 10 build 19041

my .ftpconfig:
{
    "protocol": "sftp",
    "host": "intax2001",
    "port": 22,
    "user": "XXX",
    "pass": "XXX",

    "session": "intax2001",
    "rs_name": "ifxpy",
    "rs_tags": []

}

When I have unchecked 'Use default client' so nothing starts.
When I check 'Use default client' only native WIN 10 ssh client start.

Why Putty doesn't  start me? I'm doing something wrong?

**Comment by dsone** [comment]
Please make sure that you do not report user/pw outside your context and that your server is save.

Can you start Putty from the console from anywhere else? Did you rename Putty?
If you can and you have not renamed it does sound like a problem with Remote SSH.

**Comment by arozehnal** [comment]
Yes, I can start Putty from the console.  I have the dir with Putty in the beginning of the PATH.

C:\Users\RO>where ssh
d:\U\SSH\Putty_0.67\ssh.exe

C:\Users\RO>where Putty
d:\U\SSH\Putty_0.67\PUTTY.EXE

When I have unchecked 'Use default client' only message  "Remote SSH: Starting SSH client"
appears.  Can't be this traced somehow?

**Comment by dsone** [comment]
Hmm, tracing this is difficult if there is no error display.
Try renaming `PUTTY.exe` to lowercase `putty.exe`. Remote SSH invokes the lowercase name. 
I doubt that's the culprit but there's a slight chance.

You can try to open the Dev-Console in Atom by hitting `CTRL+SHIFT+I` and now if you try to open an SSH connection via `CTRL+ALT+R` does it say anything in the console about Putty/Remote SSH?

**Comment by arozehnal** [comment]
Renaming PUTTY -> putty didn't help me.
I am able to start putty from the console (see 
![run_putty](https://user-images.githubusercontent.com/8810398/91846119-642b6a00-ec5a-11ea-96be-04866c2908a4.jpg)

The console of Atom contains only:
<URL>
C:\Users\RO\.atom\pa…ib\remote-ssh.js:44 Activating remote-ssh
C:\Users\RO\.atom\pa…ib\remote-ssh.js:97 Remote SSH - Project scanning: 360.129150390625ms
<embedded>:14 TrustedTypes policy dompurify could not be created.
C:\Users\RO\.atom\pa…ib\remote-ssh.js:97 Remote SSH - Project scanning: 1.791015625ms`

**Comment by dsone** [comment]
Really difficult to say why it's not working. Considering that RemoteSSH doesn't throw an error.
I'd say that implies everything's working as intended but bugs can be weird.
If you uncheck "useSSH" in the settings so that RSSH uses putty, we should get here: https://github.com/dsone/remote-ssh/blob/master/lib/remote-ssh.js#L270. That's the line displaying "Starting SSH".
We do not check for the `exec` return value. If that fails for whatever reason, that is highly likely out of the scope of RSSH, though.

Remote SSH builds the command depending on the settings. In your ftpconfig you have the session key set, so it should try to make putty load the session "intax2001". The command for that looks like this:
`putty -ssh -2 -load "intax2001" -pw "YourPasswordForIntax"`

If you paste this into your console, with the correct password, does Putty connect as desired?
If yes, it's definitely RemoteSSH not working but I do not know why.

Have you tried putting your credentials into the .ftpconfig and remove the session:
```
{
	"protocol": "sftp",
	"host": "your.host.name",
	"port": "22",
	"user": "XXX",
	"pass": "YYY"
}
```
Does it work that way?

**Comment by arozehnal** [comment]
I did this:
1) I tried to run Putty session from windows console - ssh -ssh -2 -load "intax2001" -l xxx -pw "yyy"
 Putty started and login+passwd was successful
2) I reinstalled RSSH plugin and Putty, I repeated previous test  (Putty from console)
3) then I run RSSH plugin and I do not believe my eyes.... Putty was started from RSSH  :-)
however, the login was not performed (I had credentials in the .ftpconfig)
just login challenge appears
4) I removed the session: from .ftpconfig
   RSSH plugin launched Putty and entered login name, but did not insert passwd.

**Comment by arozehnal** [comment]
I changed my Putty session - I filled Autologin field in Putty configuration.
Now Putty is started and login sequence is OK finished.
We will probably close this issue.

**Comment by dsone** [comment]
If you reinstalled RSSH, its setting might be set back to "copy password" instead of using the password as a parameter.
So a right click in the opening console window should paste the password into it.

I'm glad you were able to solve the issue.
Thank you for your feedback, patience and for trying out Remote-SSH!
